# Site settings
title: cxtBlog
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lemon8.top" # the base hostname & protocol for your site

author:
  fullname: chen xuting
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: chenxtdo
  # twitter: electrik_frog
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: rdiscount